global:
  scrape_interval: 15s

scrape_configs:
  - job_name: 'wordpress'
    metrics_path: /metrics
    static_configs:
      - targets: ['wordpress:80']

  - job_name: 'mysqld-exporter'
    static_configs:
      - targets: ['mysqld-exporter:9104']

  - job_name: 'redis_exporter'
    static_configs:
      - targets: ['redis_exporter:9121']
