# Use a imagem base do WordPress
FROM wordpress:latest

# Instalação do Plugin Redis Object Cache usando WP-CLI
RUN curl -O https://raw.githubusercontent.com/wp-cli/builds/gh-pages/phar/wp-cli.phar \
    && chmod +x wp-cli.phar \
    && mv wp-cli.phar /usr/local/bin/wp

# Criação do diretório de plugins (se necessário)
RUN mkdir -p /var/www/html/wp-content/plugins/meu-plugin

# Copia o script de instalação para o contêiner
COPY install-plugin.sh /usr/local/bin/
RUN chmod +x /usr/local/bin/install-plugin.sh

# Define o diretório de trabalho para onde o WordPress está instalado
WORKDIR /var/www/html/wp-content/plugins/meu-plugin

# Executa o script de instalação como ponto de entrada
ENTRYPOINT ["sh", "/usr/local/bin/install-plugin.sh"]


