services:
  wordpress:
    build: .
    volumes:
      - ./src:/var/www/html/wp-content/plugins/meu-plugin
    networks:
      - back
    environment:
      WORDPRESS_DB_HOST: db
      WORDPRESS_DB_USER: wpuser
      WORDPRESS_DB_PASSWORD: wppass
      WORDPRESS_DB_NAME: wpdb
    restart: on-failure
    ports:
      - "8080:80"

  db:
    image: mysql:latest
    volumes:
      - db:/var/lib/mysql
    networks:
      - back
    environment:
      MYSQL_DATABASE: wpdb
      MYSQL_USER: wpuser
      MYSQL_PASSWORD: wppass
      MYSQL_RANDOM_ROOT_PASSWORD: '1'
    restart: on-failure

  adminer:
    depends_on:
      - db
    image: adminer:latest
    networks:
      - back
    ports:
      - "8081:8080"

    phpmyadmin:
      depends_on:
        - db
      image: phpmyadmin:latest
      networks:
        - back
      environment:
        PMA_HOST: db
        MYSQL_ROOT_PASSWORD: wppass
      ports:
        - "8082:80"

  redis:
    image: redis:latest
    networks:
      - back 

  prometheus:
    image: prom/prometheus:latest
    networks:
      - back
    volumes:
      - ./prometheus:/etc/prometheus
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
    ports:
      - "9090:9090"

  mysql-exporter:
    image: prom/mysqld-exporter
    networks:
      - back
    volumes:
      - "./.my.cnf:/etc/mysql_exporter/.my.cnf:ro"
    command:
      - --config.my-cnf=/etc/mysql_exporter/.my.cnf
      - --mysqld.address=db:3306
    ports:
      - "9104:9104"

  redis_exporter:
    image: oliver006/redis_exporter:latest
    networks:
      - back
    environment:
      REDIS_ADDR: redis:6379
    ports:
      - "9121:9121" 

networks:
  back:

volumes:
  db:
