version: '3.3'

services:
  wordpress:
    image: wordpress:latest
    volumes:
      - ./src:/var/www/html/wp-content/plugins/meu-plugin
    networks:
      - back
    environment:
      WORDPRESS_DB_HOST: db
      WORDPRESS_DB_USER: wpuser
      WORDPRESS_DB_PASSWORD: wppass
      WORDPRESS_DB_NAME: wpdb
    restart: on-failure
    ports:
      - "8080:80"

  db:
    image: mysql:latest
    volumes:
      - db:/var/lib/mysql
    networks:
      - back
    environment:
      MYSQL_DATABASE: wpdb
      MYSQL_USER: wpuser
      MYSQL_PASSWORD: wppass
      MYSQL_RANDOM_ROOT_PASSWORD: '1'
    restart: on-failure

  adminer:
    depends_on:
      - db
    image: adminer:latest
    networks:
      - back
    ports:
      - "8081:8080"

  prometheus:
    image: prom/prometheus:latest
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
    networks:
      - back
    ports:
      - "9090:9090"

networks:
  back:

volumes:
  db:
