version: '3.8'
services:
  wordpress:
    image: wordpress:latest
    build: .
    volumes:
      - ./src:/var/www/html/wp-content/plugins/meu-plugin
    networks:
      - back
    environment:
      WORDPRESS_DB_HOST: db
      WORDPRESS_DB_USER: wpuser
      WORDPRESS_DB_PASSWORD: wppass
      WORDPRESS_DB_NAME: wpdb
    restart: on-failure
    ports:
      - "8080:80"

  db:
    image: mysql:latest
    volumes:
      - db:/var/lib/mysql
    networks:
      - back
    environment:
      MYSQL_DATABASE: wpdb
      MYSQL_USER: wpuser
      MYSQL_PASSWORD: wppass
      MYSQL_RANDOM_ROOT_PASSWORD: '1'
    restart: on-failure

  adminer:
    depends_on:
      - db
    image: adminer:latest
    networks:
      - back
    ports:
      - "8081:8080"

  redis:
    image: redis:latest
    networks:
      - back

  prometheus:
    depends_on:
      - db
    image: prom/prometheus:latest
    networks:
      - back
    volumes:
      - ./prometheus:/etc/prometheus
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
    ports:
      - "9090:9090"

  cadvisor:
    image: gcr.io/cadvisor/cadvisor:latest
    volumes:
      - /:/rootfs:ro
      - /var/run:/var/run:rw
      - /sys:/sys:ro
      - /mnt/docker-data:/var/lib/docker:ro
    ports:
      - "8084:8080"
    networks:
      - back

  mysqld-exporter:
    depends_on:
      - db
    image: prom/mysqld-exporter
    networks:
      - back
    volumes:
      - "./.my.cnf:/cfg/.my.cnf:ro"
    command:
      - --config.my-cnf=/cfg/.my.cnf
      - --mysqld.address=db:3306
    ports:
      - "9104:9104"

  redis_exporter:
    depends_on:
      - db
    image: oliver006/redis_exporter:latest
    networks:
      - back
    environment:
      REDIS_ADDR: redis:6379
    ports:
      - "9121:9121"

  node-exporter:
    image: prom/node-exporter
    volumes:
      - /proc:/host/proc:ro
      - /sys:/host/sys:ro
      - /:/rootfs:ro
    command:
      - '--path.procfs=/host/proc'
      - '--path.sysfs=/host/sys'
      - '--collector.filesystem.ignored-mount-points=^/host/proc,/host/sys,/etc'
    ports:
      - "9100:9100"
    networks:
      - back

networks:
  back:

volumes:
  db:
