FROM wordpress:latest

# Instalar o Plugin Redis Object Cache
RUN curl -O https://raw.githubusercontent.com/wp-cli/builds/gh-pages/phar/wp-cli.phar \
    && chmod +x wp-cli.phar \
    && mv wp-cli.phar /usr/local/bin/wp

# Copiar o script de instalação para o contêiner
COPY ../install-plugin.sh /usr/local/bin/
RUN chmod +x /usr/local/bin/install-plugin.sh

# Definir o script como ponto de entrada
ENTRYPOINT ["sh", "/usr/local/bin/install-plugin.sh"]

